variables:
  TEST_FOLDER: 'CoreTest\\bin\\Release'  
  NUGET_PATH: 'C:\\Git\\NuGet\\nuget.exe'
  MSBUILD_PATH: 'C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\msbuild.exe'
  xUNIT_PATH: 'packages\\xunit.runner.console.2.3.1\\tools\\net452\\xunit.console.exe'
  DEFAULT_SLN: 'GoCWebTemplates.sln'
  SAMPLES_SLN: 'GoC.WebTemplates.Samples.sln'
  
stages:
  - buildDefaultSln
  - test

build_default_sln:
  stage: buildDefaultSln
  script:
    - echo "Restoring NuGet packages..."
    - '"%NUGET_PATH%" restore %DEFAULT_SLN%'
    - echo "Building the solution..."
    - '"%MSBUILD_PATH%" %DEFAULT_SLN% /p:Configuration=Release'
  artifacts:
    expire_in: 1 hour
    paths:
      - '%TEST_FOLDER%'
      - 'packages'

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - '"%xUNIT_PATH%" %TEST_FOLDER%\\CoreTest.dll"'
  dependencies:
    - build_default_sln