build_sln:
  stage: build
  tags:
    - nuget
    - msbuild
    - secrets
  script:
    - 'copy %SECRETS_PATH%\\GoC.WebTemplate.snk .'
    - '"%NUGET_PATH%" restore %DEFAULT_SLN%'
    - '"%MSBUILD_PATH%" %DEFAULT_SLN% /p:Configuration=Release'
    - 'del GoC.WebTemplate.snk'
  artifacts:
    expire_in: 1 hour
    paths:
      - 'GoC.WebTemplate.Components\\bin\\Release\\netstandard2.0\\GoC.WebTemplate.Components.dll'
      - 'GoC.WebTemplate.Components.Core\\bin\\Release\\netcoreapp2.1\\GoC.WebTemplate.Components.Core.dll'
      - 'GoC.WebTemplate.Components.Framework\\bin\\Release\\GoC.WebTemplate.Components.Framework.dll'

build_sample:
  stage: build
  tags:
    - nuget
    - msbuild
  script:
    - '"%NUGET_PATH%" restore %SAMPLES_SLN%'
    - '"%MSBUILD_PATH%" %SAMPLES_SLN% /p:Configuration=Release'