package_components:
  stage: package
  dependencies: 
    - version_components
    - build_default
  tags:
    - nuget
  only:
    - tags
    - master
  script:
    - powershell.exe "%PACKAGE_PS1%" "Components\\WebTemplateCore" "GoC.WebTemplate-Components"
    - '"%NUGET_PATH%" pack "Components\\WebTemplateCore\\GoC.WebTemplate-Components.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-Components.%CI_COMMIT_REF_NAME%.nupkg'

package_mvc:
  stage: package
  dependencies: 
    - version_mvc
    - build_default
  tags:
    - nuget
  only:
    - tags
    - master
  script:       
    - powershell.exe "%PACKAGE_PS1%" "Applications\\GoC.WebTemplateMVC" "GoC.WebTemplate-MVC"
    - '"%NUGET_PATH%" pack "Applications\\GoC.WebTemplateMVC\\GoC.WebTemplate-MVC.nuspec"'
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-MVC.%CI_COMMIT_REF_NAME%.nupkg'
      
package_forms:
  stage: package
  dependencies: 
    - version_forms
    - build_default
  tags:
    - nuget
  only:
    - tags
    - master
  script:   
    - powershell.exe "%PACKAGE_PS1%" "Applications\\GoC.WebTemplate" "GoC.WebTemplate-WebForms"
    - '"%NUGET_PATH%" pack "Applications\\GoC.WebTemplate\\GoC.WebTemplate-WebForms.nuspec"'    
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-WebForms.%CI_COMMIT_REF_NAME%.nupkg'

package_mvc_sample:
  stage: package
  dependencies: 
    - version_mvc_sample
    - build_sample
  tags:
    - nuget
  only:
    - tags
    - master
  script:      
    - powershell.exe "%PACKAGE_PS1%" "SampleCode\\GoC.WebTemplate-MVC.Sample" "GoC.WebTemplate-MVC.Sample"
    - '"%NUGET_PATH%" pack "SampleCode\\GoC.WebTemplate-MVC.Sample\\GoC.WebTemplate-MVC.Sample.nuspec"' 
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-MVC.Sample.%CI_COMMIT_REF_NAME%.nupkg'

package_forms_sample:
  stage: package
  dependencies: 
    - version_froms_sample
    - build_sample
  tags:
    - nuget
  only:
    - tags
    - master
  script:      
    - powershell.exe "%PACKAGE_PS1%" "SampleCode\\GoC.WebTemplate-WebForms.Sample" "GoC.WebTemplate-WebForms.Sample"
    - '"%NUGET_PATH%" pack "SampleCode\\GoC.WebTemplate-WebForms.Sample\\GoC.WebTemplate-WebForms.Sample.nuspec"' 
  artifacts:
    expire_in: 1 day
    paths:
      - 'GoC.WebTemplate-WebForms.Sample.%CI_COMMIT_REF_NAME%.nupkg'