test_components_core:
  stage: test
  script:
    - 'dotnet test GoC.WebTemplate.Components.Core.Tests'

test_components_frame:
  stage: test
  script:
    - 'dotnet test GoC.WebTemplate.Components.Framework.Tests'

code_quality_components:
  stage: test
  allow_failure: true
  tags:
    - nuget
    - msbuild
  script:
    - '"%NUGET_PATH%" restore GoC.WebTemplate.Components\GoC.WebTemplate.Components.csproj'
    - '"%MSBUILD_PATH%" GoC.WebTemplate.Components\GoC.WebTemplate.Components.csproj /p:RunCodeAnalysis=true /p:CodeAnalysisLogFile=DefaultCodeAnalysisReport.xml'
  except:
    - tags
    - master
  artifacts:    
    expire_in: 1 week
    paths: 
      - GoC.WebTemplate.Components\DefaultCodeAnalysisReport.xml

code_quality_samples:
  stage: test
  allow_failure: true
  tags:
    - nuget
    - msbuild
  script:
    - '"%NUGET_PATH%" restore %SAMPLES_SLN%'
    - '"%MSBUILD_PATH%" %SAMPLES_SLN% /p:RunCodeAnalysis=true /p:CodeAnalysisLogFile=SamplesCodeAnalysisReport.xml'
  except:
    - tags
    - master
  artifacts:    
    expire_in: 1 week
    paths: 
      - SampleCode\GoC.WebTemplate-MVC.Sample\SamplesCodeAnalysisReport.xml
      - SampleCode\GoC.WebTemplate-WebForms.Sample\SamplesCodeAnalysisReport.xml
