test_components:
  stage: test
  tags:
    - secrets
  script:
    - 'copy %SECRETS_PATH%\\GoC.WebTemplate.snk .'
    - 'dotnet test GoC.WebTemplate.Components.Tests'
    - 'del GoC.WebTemplate.snk'

test_components_core:
  stage: test
  script:
    - 'dotnet test GoC.WebTemplate.Components.Core.Tests'

test_components_frame:
  stage: test
  dependencies:
    - build_sln
  script:
    - '"%xUNIT_PATH%\\xunit.console.exe" "%TEST_FRAME_PATH%\\GoC.WebTemplate.Components.Framework.Tests.dll"'


code_quality_samples:
  stage: test
  allow_failure: true
  tags:
    - nuget
    - msbuild
  script:
    - '"%NUGET_PATH%" restore %SAMPLES_SLN%'
    - '"%MSBUILD_PATH%" %SAMPLES_SLN% /p:RunCodeAnalysis=true /p:CodeAnalysisLogFile=SamplesCodeAnalysisReport.xml'
  except:
    - tags
    - master
  artifacts:    
    expire_in: 1 week
    paths: 
      - SampleCode\GoC.WebTemplate-MVC.Sample\SamplesCodeAnalysisReport.xml
      - SampleCode\GoC.WebTemplate-WebForms.Sample\SamplesCodeAnalysisReport.xml
