version_components:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "Components\Components.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'Components\Components.csproj'

version_componentscore:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "Components.Core\Components.Core.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'Components.Core\Components.Core.csproj'

version_componentsframe:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "Components.Framework\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'Components.Framework\Properties\AssemblyInfo.cs'

version_coremvc:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %DOTNET_VERSION_PS% %MAIN_VERSION% "CoreMVC\CoreMVC.csproj"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'CoreMVC\CoreMVC.csproj'

version_forms:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "WebForms\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'WebForms\Properties\AssemblyInfo.cs'

version_mvc:
  stage: prepare
  allow_failure: true
  only:
    variables:
      - $MAIN_VERSION != null
  script:    
    - powershell.exe %VERSION_PS1% %MAIN_VERSION% "MVC\Properties\AssemblyInfo.cs"
  artifacts:
    expire_in: 1 hour
    paths:
      - 'MVC\Properties\AssemblyInfo.cs' 
